services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  loader:
    build:
      context: ./application/loader
    volumes:
      - ./application/loader:/app
      - ./share:/share
      - ./data:/data
    environment:
      - PYTHONPATH=/app:/share
      - PDF_PATH=${PDF_PATH:-/data/book}
      - QDRANT_HOST=qdrant
      - MONGO_URI=mongodb://mongo:27017
    restart: unless-stopped
    depends_on:
      - qdrant
      - mongo

volumes:
  mongo_data:
  qdrant_data:
