services:
  agent:
    build:
      context: ./application/agent
    volumes:
      - ./application/agent:/app
      - ./share:/share
    environment:
      - PYTHONPATH=/app:/share
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    depends_on:
      - archivist
      - historian

  archivist:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  ficher:
    build:
      context: ./application/ficher
    volumes:
      - ./application/ficher:/app
      - ./share:/share
      - ./data:/data
    environment:
      - PYTHONPATH=/app:/share
    command: python main.py

  historian:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  librarian:
    build:
      context: ./application/librarian
    volumes:
      - ./application/librarian:/app
      - ./share:/share
    environment:
      - PYTHONPATH=/app:/share
    command: streamlit run main.py --server.port=8501
    ports:
      - "8501:8501"
