[project]
name = "BiblioQuiz"
version = "0.1.0"
description = "Search your eBooks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []


[tool.uv.workspace]
members = [
    "application/agent",
    "application/loader",
    "application/historian",
    "application/librarian",
    "share",
]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "B"]
exclude = ["__pycache__", ".venv"]
