[tool.poetry]
name = "biblioquiz-orchestrator"
version = "0.1.0"
description = "Retrieve information from library (PDF books)"
readme = "README.md"
authors = ["AxlER8R <axl@axler8r.io>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
autogen-agentchat = "^0.6.1"
autogen-ext = {extras = ["openai"], version = "^0.6.1"}

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
