[tool.poetry]
name = "biblioquiz-shared"
version = "0.1.0"
description = "Shared utilities for BiblioQuiz services"
readme = "README.md"
authors = ["AxlER8R <axl@axler8r.io>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
